// src/components/EditModal.tsx
import { useState } from "react"
import type { Item, TabType } from "@/types"

interface EditModalProps {
	item: Item
	type: TabType
	onClose: () => void
	onSave: (id: number, updates: Partial<Item>) => void
}

interface FormState {
	title: string
	director: string
	creator: string
	author: string
	year: string | number
	genre: string
	actors: string
	country: string
	source: string
	seasons: string | number
	watched: boolean
	rating: number
}

const EditModal = ({ item, type, onClose, onSave }: EditModalProps) => {
	const isFilm = type === "films"
	const isSeries = type === "series"
	const isMedia = isFilm || isSeries

	const [form, setForm] = useState<FormState>({
		title: item.title || "",
		director: "director" in item ? item.director || "" : "",
		creator: "creator" in item ? item.creator || "" : "",
		author: "author" in item ? item.author || "" : "",
		year: item.year || "",
		genre: item.genre || "",
		actors: "actors" in item ? item.actors || "" : "",
		country: "country" in item ? item.country || "" : "",
		source: item.source || "",
		seasons: "seasons" in item ? item.seasons || "" : "",
		watched: item.watched || false,
		rating: item.rating || 0,
	})

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault()
		if (!form.title) return
		onSave(item.id, {
			...form,
			year: parseInt(String(form.year), 10) || item.year,
			seasons: form.seasons
				? parseInt(String(form.seasons), 10)
				: undefined,
			rating: form.rating || undefined,
		} as Partial<Item>)
	}

	return (
		// biome-ignore lint/a11y/noStaticElementInteractions: modal backdrop
		// biome-ignore lint/a11y/useKeyWithClickEvents: modal backdrop pattern
		<div className="modal-bg" onClick={onClose}>
			<div
				className="modal add-modal"
				onClick={(e) => e.stopPropagation()}
				onKeyDown={(e) => e.stopPropagation()}
				role="dialog"
				aria-modal="true"
			>
				<div className="modal-head">
					<div className="modal-title">Modifier</div>
					<button type="button" className="modal-close" onClick={onClose}>
						×
					</button>
				</div>
				<div className="modal-body">
					<form onSubmit={handleSubmit}>
						<div className="form-grid">
							<label className="full">
								<span>Titre *</span>
								<input
									type="text"
									value={form.title}
									onChange={(e) => setForm({ ...form, title: e.target.value })}
									required
								/>
							</label>
							<label>
								<span>
									{isFilm ? "Réalisateur" : isSeries ? "Créateur" : "Auteur"}
								</span>
								<input
									type="text"
									value={
										isFilm
											? form.director
											: isSeries
												? form.creator
												: form.author
									}
									onChange={(e) =>
										setForm({
											...form,
											[isFilm ? "director" : isSeries ? "creator" : "author"]:
												e.target.value,
										})
									}
								/>
							</label>
							<label>
								<span>Année</span>
								<input
									type="number"
									value={form.year}
									onChange={(e) => setForm({ ...form, year: e.target.value })}
								/>
							</label>
							{isSeries && (
								<label>
									<span>Saisons</span>
									<input
										type="number"
										value={form.seasons}
										onChange={(e) =>
											setForm({ ...form, seasons: e.target.value })
										}
									/>
								</label>
							)}
							<label className={isSeries ? "" : "full"}>
								<span>Genre</span>
								<input
									type="text"
									value={form.genre}
									onChange={(e) => setForm({ ...form, genre: e.target.value })}
									placeholder={isMedia ? "Drame, Action..." : "Roman, SF..."}
								/>
							</label>
							{isMedia && (
								<label className="full">
									<span>Casting</span>
									<input
										type="text"
										value={form.actors}
										onChange={(e) =>
											setForm({ ...form, actors: e.target.value })
										}
									/>
								</label>
							)}
							<label className="full">
								<span>Source / Reco</span>
								<input
									type="text"
									value={form.source}
									onChange={(e) => setForm({ ...form, source: e.target.value })}
									placeholder="Reco ami..."
								/>
							</label>
							<label className="checkbox">
								<input
									type="checkbox"
									checked={form.watched}
									onChange={(e) =>
										setForm({ ...form, watched: e.target.checked })
									}
								/>
								<span>{isMedia ? "Vu" : "Lu"}</span>
							</label>
							{form.watched && (
								<div className="form-field">
									<span>Note</span>
									<div className="rating-input">
										{[1, 2, 3, 4, 5].map((n) => (
											<button
												key={n}
												type="button"
												className={`star ${form.rating >= n ? "active" : ""}`}
												onClick={() =>
													setForm({
														...form,
														rating: form.rating === n ? 0 : n,
													})
												}
											>
												★
											</button>
										))}
									</div>
								</div>
							)}
						</div>

						<div className="form-actions">
							<button
								type="button"
								className="btn btn-secondary"
								onClick={onClose}
							>
								Annuler
							</button>
							<button type="submit" className="btn btn-primary">
								Enregistrer
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	)
}

export default EditModal

// frontend-cinematheque/src/lib/components/EditModal.svelte
<script lang="ts">
import type { Item, TabType } from "$lib/types"
import { isConsumed } from "$lib/types"

let {
	item,
	type,
	onClose,
	onSave,
}: {
	item: Item
	type: TabType
	onClose: () => void
	onSave: (id: number, updates: Partial<Item>) => void
} = $props()

const isFilm = $derived(type === "films" || type === "documentaries")
const isSeries = $derived(type === "series")
const isMedia = $derived(isFilm || isSeries)

interface FormState {
	title: string
	director: string
	creator: string
	author: string
	year: string | number
	country: string
	recommendation_source: string
	seasons: string | number
	watched: boolean
	rating: number
}

let form = $state<FormState>({
	title: item.title || "",
	director: "director" in item ? item.director || "" : "",
	creator: "creator" in item ? item.creator || "" : "",
	author: "author" in item ? item.author || "" : "",
	year: item.year || "",
	country: "country" in item ? item.country || "" : "",
	recommendation_source: item.recommendation_source || "",
	seasons: "seasons" in item ? item.seasons || "" : "",
	watched: isConsumed(item),
	rating: item.rating || 0,
})

function handleSubmit(e: SubmitEvent) {
	e.preventDefault()
	if (!form.title) return
	const { watched, ...rest } = form
	onSave(item.id, {
		...rest,
		year: parseInt(String(form.year), 10) || item.year,
		seasons: form.seasons ? parseInt(String(form.seasons), 10) : undefined,
		rating: form.rating || undefined,
		consumed_at: watched ? item.consumed_at || new Date().toISOString() : null,
	} as Partial<Item>)
}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="modal-bg" onclick={onClose} onkeydown={() => {}} role="presentation">
	<div
		class="modal add-modal"
		onclick={(e) => e.stopPropagation()}
		onkeydown={(e) => e.stopPropagation()}
		role="dialog"
		aria-modal="true"
	>
		<div class="modal-head">
			<div class="modal-title">Edit</div>
			<button type="button" class="modal-close" onclick={onClose}>×</button>
		</div>
		<div class="modal-body">
			<form onsubmit={handleSubmit}>
				<div class="form-grid">
					<label class="full">
						<span>Title *</span>
						<input type="text" bind:value={form.title} required />
					</label>
					<label>
						<span>{isFilm ? "Director" : isSeries ? "Creator" : "Author"}</span>
						{#if isFilm}
							<input type="text" bind:value={form.director} />
						{:else if isSeries}
							<input type="text" bind:value={form.creator} />
						{:else}
							<input type="text" bind:value={form.author} />
						{/if}
					</label>
					<label>
						<span>Year</span>
						<input type="number" bind:value={form.year} />
					</label>
					{#if isSeries}
						<label>
							<span>Seasons</span>
							<input type="number" bind:value={form.seasons} />
						</label>
					{/if}
					<label class="full">
						<span>Country</span>
						<input type="text" bind:value={form.country} />
					</label>
					<label class="full">
						<span>Source / recommendation</span>
						<input
							type="text"
							bind:value={form.recommendation_source}
							placeholder="Friend tip..."
						/>
					</label>
					<label class="checkbox">
						<input type="checkbox" bind:checked={form.watched} />
						<span>{isMedia ? "Watched" : "Read"}</span>
					</label>
					{#if form.watched}
						<div class="form-field">
							<span>Rating</span>
							<div class="rating-input">
								{#each [1, 2, 3, 4, 5] as n (n)}
									<button
										type="button"
										class="star"
										class:active={form.rating >= n}
										onclick={() =>
											(form.rating = form.rating === n ? 0 : n)}
									>
										★
									</button>
								{/each}
							</div>
						</div>
					{/if}
				</div>

				<div class="form-actions">
					<button type="button" class="btn btn-secondary" onclick={onClose}>
						Cancel
					</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
