// frontend/src/components/layout/Header.tsx
import type { FilterType, SortType, TabType, ViewType } from "@/types"

interface HeaderProps {
	// Stats
	stats: { total: number; watched: number }
	syncing: boolean
	posterProgress: string
	onAddClick: () => void

	// Tabs
	tab: TabType
	onTabChange: (tab: TabType) => void
	counts: { movies: number; series: number; books: number; comics: number }

	// Search & Filters
	search: string
	onSearchChange: (value: string) => void
	filter: FilterType
	onFilterChange: (filter: FilterType) => void
	genre: string
	onGenreChange: (genre: string) => void
	genres: string[]

	// Sort & View
	sort: SortType
	onSortChange: (sort: SortType) => void
	view: ViewType
	onViewChange: (view: ViewType) => void
	showSeparators: boolean
	onShowSeparatorsChange: (show: boolean) => void
	cardSize: number
	onCardSizeChange: (size: number) => void
}

const Header = ({
	stats,
	syncing,
	posterProgress,
	onAddClick,
	tab,
	onTabChange,
	counts,
	search,
	onSearchChange,
	filter,
	onFilterChange,
	genre,
	onGenreChange,
	genres,
	sort,
	onSortChange,
	view,
	onViewChange,
	showSeparators,
	onShowSeparatorsChange,
	cardSize,
	onCardSizeChange,
}: HeaderProps) => {
	const isReadType = tab === "books" || tab === "comics"

	const handleTabChange = (newTab: TabType) => {
		onTabChange(newTab)
		onGenreChange("")
	}

	return (
		<header className="header">
			<div className="header-top">
				<div className="logo">
					ma <span>collection</span>
				</div>
				<div className="header-right">
					<div className="stats">
						<b>{stats.total}</b> {tab} · <b>{stats.watched}</b>{" "}
						{isReadType
							? stats.watched > 1
								? "lus"
								: "lu"
							: stats.watched > 1
								? "vus"
								: "vu"}
						{syncing && <span className="sync-icon"> ⟳</span>}
					</div>
					<button type="button" className="add-btn" onClick={onAddClick}>
						+ Ajouter
					</button>
				</div>
			</div>

			{posterProgress && (
				<div className="poster-progress">
					Téléchargement des affiches... {posterProgress}
				</div>
			)}

			<div className="tabs">
				<button
					type="button"
					className={`tab ${tab === "films" ? "active" : ""}`}
					onClick={() => handleTabChange("films")}
				>
					Movies <span className="tab-count">{counts.movies}</span>
				</button>
				<button
					type="button"
					className={`tab ${tab === "series" ? "active" : ""}`}
					onClick={() => handleTabChange("series")}
				>
					Séries <span className="tab-count">{counts.series}</span>
				</button>
				<button
					type="button"
					className={`tab ${tab === "books" ? "active" : ""}`}
					onClick={() => handleTabChange("books")}
				>
					Livres <span className="tab-count">{counts.books}</span>
				</button>
				<button
					type="button"
					className={`tab ${tab === "comics" ? "active" : ""}`}
					onClick={() => handleTabChange("comics")}
				>
					BD <span className="tab-count">{counts.comics}</span>
				</button>
			</div>

			<div className="controls">
				<input
					className="search-box"
					placeholder="Rechercher..."
					value={search}
					onChange={(e) => onSearchChange(e.target.value)}
				/>
				<div className="filter-divider" />
				<button
					type="button"
					className={`filter-btn ${filter === "all" ? "active" : ""}`}
					onClick={() => onFilterChange("all")}
				>
					Tous
				</button>
				<button
					type="button"
					className={`filter-btn ${filter === "unwatched" ? "active" : ""}`}
					onClick={() => onFilterChange("unwatched")}
				>
					{isReadType ? "À lire" : "À voir"}
				</button>
				<button
					type="button"
					className={`filter-btn ${filter === "watched" ? "active" : ""}`}
					onClick={() => onFilterChange("watched")}
				>
					{isReadType ? "Lus" : "Vus"}
				</button>
				<div className="filter-divider" />
				<select value={genre} onChange={(e) => onGenreChange(e.target.value)}>
					<option value="">Genre</option>
					{genres.map((g) => (
						<option key={g} value={g}>
							{g}
						</option>
					))}
				</select>
				<select
					value={sort}
					onChange={(e) => onSortChange(e.target.value as SortType)}
					className="sort-select"
				>
					<option value="year-desc">Année ↓</option>
					<option value="year-asc">Année ↑</option>
					<option value="alpha-asc">A → Z</option>
					<option value="alpha-desc">Z → A</option>
					<option value="director">
						{tab === "films"
							? "Réalisateur"
							: tab === "series"
								? "Créateur"
								: "Auteur"}
					</option>
					<option value="added">Récents</option>
					<option value="unwatched">{isReadType ? "Non lus" : "Non vus"}</option>
				</select>
				<div className="view-controls">
					<button
						type="button"
						className={`view-btn ${view === "grid" ? "active" : ""}`}
						onClick={() => onViewChange("grid")}
					>
						▦
					</button>
					<button
						type="button"
						className={`view-btn ${view === "list" ? "active" : ""}`}
						onClick={() => onViewChange("list")}
					>
						☰
					</button>
					<button
						type="button"
						className={`view-btn ${showSeparators ? "active" : ""}`}
						onClick={() => onShowSeparatorsChange(!showSeparators)}
						title="Séparateurs"
					>
						―
					</button>
					{view === "grid" && (
						<input
							type="range"
							className="size-slider"
							min="80"
							max="160"
							value={cardSize}
							onChange={(e) => onCardSizeChange(Number(e.target.value))}
						/>
					)}
				</div>
			</div>
		</header>
	)
}

export default Header

// frontend-cinematheque/src/lib/components/Header.svelte
<script lang="ts">
import {
	type FilterType,
	type SortType,
	type TabType,
	tabLabelEn,
	type ViewType,
} from "$lib/types"

let {
	stats,
	syncing,
	posterProgress,
	onAddClick,
	tab,
	onTabChange,
	counts,
	search,
	onSearchChange,
	filter,
	onFilterChange,
	sort,
	onSortChange,
	view,
	onViewChange,
	showSeparators,
	onShowSeparatorsChange,
	cardSize,
	onCardSizeChange,
}: {
	stats: { total: number; watched: number }
	syncing: boolean
	posterProgress: string
	onAddClick: () => void
	tab: TabType
	onTabChange: (t: TabType) => void
	counts: {
		movies: number
		documentaries: number
		series: number
		books: number
		comics: number
	}
	search: string
	onSearchChange: (v: string) => void
	filter: FilterType
	onFilterChange: (f: FilterType) => void
	sort: SortType
	onSortChange: (s: SortType) => void
	view: ViewType
	onViewChange: (v: ViewType) => void
	showSeparators: boolean
	onShowSeparatorsChange: (v: boolean) => void
	cardSize: number
	onCardSizeChange: (n: number) => void
} = $props()

const isReadType = $derived(tab === "books" || tab === "comics")
</script>

<header class="header">
	<div class="header-top">
		<div class="logo">
			my <span>collection</span>
		</div>
		<div class="header-right">
			<div class="stats">
				<b>{stats.total}</b>
				{tabLabelEn(tab)} · <b>{stats.watched}</b>
				{isReadType ? "read" : "watched"}
				{#if syncing}<span class="sync-icon"> ⟳</span>{/if}
			</div>
			<button type="button" class="add-btn" onclick={onAddClick}>+ Add</button>
		</div>
	</div>

	{#if posterProgress}
		<div class="poster-progress">
			Downloading posters... {posterProgress}
		</div>
	{/if}

	<div class="tabs">
		<button
			type="button"
			class="tab"
			class:active={tab === "films"}
			onclick={() => onTabChange("films")}
		>
			Movies <span class="tab-count">{counts.movies}</span>
		</button>
		<button
			type="button"
			class="tab"
			class:active={tab === "documentaries"}
			onclick={() => onTabChange("documentaries")}
		>
			Documentaries <span class="tab-count">{counts.documentaries}</span>
		</button>
		<button
			type="button"
			class="tab"
			class:active={tab === "series"}
			onclick={() => onTabChange("series")}
		>
			Series <span class="tab-count">{counts.series}</span>
		</button>
		<button
			type="button"
			class="tab"
			class:active={tab === "books"}
			onclick={() => onTabChange("books")}
		>
			Books <span class="tab-count">{counts.books}</span>
		</button>
		<button
			type="button"
			class="tab"
			class:active={tab === "comics"}
			onclick={() => onTabChange("comics")}
		>
			Comics <span class="tab-count">{counts.comics}</span>
		</button>
	</div>

	<div class="controls">
		<input
			class="search-box"
			placeholder="Search..."
			value={search}
			oninput={(e) => onSearchChange(e.currentTarget.value)}
		/>
		<div class="filter-divider"></div>
		<button
			type="button"
			class="filter-btn"
			class:active={filter === "all"}
			onclick={() => onFilterChange("all")}
		>
			All
		</button>
		<button
			type="button"
			class="filter-btn"
			class:active={filter === "unwatched"}
			onclick={() => onFilterChange("unwatched")}
		>
			{isReadType ? "To read" : "To watch"}
		</button>
		<button
			type="button"
			class="filter-btn"
			class:active={filter === "watched"}
			onclick={() => onFilterChange("watched")}
		>
			{isReadType ? "Read" : "Watched"}
		</button>
		<div class="filter-divider"></div>
		<select
			value={sort}
			onchange={(e) => onSortChange(e.currentTarget.value as SortType)}
			class="sort-select"
		>
			<option value="year-desc">Year ↓</option>
			<option value="year-asc">Year ↑</option>
			<option value="alpha-asc">A → Z</option>
			<option value="alpha-desc">Z → A</option>
			<option value="director">
				{tab === "films" || tab === "documentaries"
					? "Director"
					: tab === "series"
						? "Creator"
						: "Author"}
			</option>
			<option value="added">Recently added</option>
			<option value="unwatched">{isReadType ? "Unread" : "Unwatched"}</option>
		</select>
		<div class="view-controls">
			<button
				type="button"
				class="view-btn"
				class:active={view === "grid"}
				onclick={() => onViewChange("grid")}
			>
				▦
			</button>
			<button
				type="button"
				class="view-btn"
				class:active={view === "list"}
				onclick={() => onViewChange("list")}
			>
				☰
			</button>
			<button
				type="button"
				class="view-btn"
				class:active={showSeparators}
				onclick={() => onShowSeparatorsChange(!showSeparators)}
				title="Separators"
			>
				―
			</button>
			{#if view === "grid"}
				<input
					type="range"
					class="size-slider"
					min="80"
					max="160"
					value={cardSize}
					oninput={(e) => onCardSizeChange(Number(e.currentTarget.value))}
				/>
			{/if}
		</div>
	</div>
</header>
