// src/components/ItemCard.tsx
import type { Item } from "@/types"
import { getSmallPoster } from "@/utils/poster"

interface ItemCardProps {
	item: Item
	onSelect: (item: Item) => void
	onToggleWatch: (id: number, e: React.MouseEvent) => void
}

const ItemCard = ({ item, onSelect, onToggleWatch }: ItemCardProps) => {
	return (
		<button
			type="button"
			className={`card ${item.watched ? "is-watched" : "is-unwatched"}`}
			onClick={() => onSelect(item)}
		>
			{item.poster ? (
				<>
					<img
						className="card-img"
						src={getSmallPoster(item.poster) ?? undefined}
						alt={item.title}
						loading="lazy"
					/>
					<div className="card-info">
						<div className="card-title">{item.title}</div>
						<div className="card-year">{item.year}</div>
					</div>
				</>
			) : (
				<div className="card-noimg">
					<div className="card-title">{item.title}</div>
					<div className="card-year">{item.year}</div>
				</div>
			)}
			{/* biome-ignore lint/a11y/useSemanticElements: styled watch button */}
			<div
				className={`watch-btn ${item.watched ? "watched" : ""}`}
				onClick={(e) => onToggleWatch(item.id, e)}
				onKeyDown={(e) => e.stopPropagation()}
				role="checkbox"
				aria-checked={item.watched}
				tabIndex={0}
			>
				✓
			</div>
		</button>
	)
}

export default ItemCard

// frontend-cinematheque/src/lib/components/ItemCard.svelte
<script lang="ts">
import { getSmallPoster } from "$lib/poster"
import type { Item } from "$lib/types"
import { isConsumed } from "$lib/types"

let {
	item,
	onSelect,
	onToggleWatch,
}: {
	item: Item
	onSelect: (item: Item) => void
	onToggleWatch: (id: number, e: MouseEvent) => void
} = $props()

const small = $derived(getSmallPoster(item.poster))
</script>

<button
	type="button"
	class="card"
	class:is-watched={isConsumed(item)}
	class:is-unwatched={!isConsumed(item)}
	onclick={() => onSelect(item)}
>
	{#if item.poster && small}
		<img class="card-img" src={small} alt={item.title} loading="lazy" />
		<div class="card-info">
			<div class="card-title">{item.title}</div>
			<div class="card-year">{item.year}</div>
		</div>
	{:else}
		<div class="card-noimg">
			<div class="card-title">{item.title}</div>
			<div class="card-year">{item.year}</div>
		</div>
	{/if}
	<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
	<div
		class="watch-btn"
		class:watched={isConsumed(item)}
		onclick={(e) => {
			e.stopPropagation()
			onToggleWatch(item.id, e)
		}}
		onkeydown={(e) => e.stopPropagation()}
		role="checkbox"
		aria-checked={isConsumed(item)}
		tabindex="0"
	>
		✓
	</div>
</button>
