// frontend-cinematheque/src/lib/components/FixPosterModal.svelte
<script lang="ts">
import { getPosterUrl } from "$lib/poster"
import { OMDB_BASE_URL, searchTMDB } from "$lib/tmdb"
import type { Item, TabType } from "$lib/types"

let {
	item,
	type,
	onClose,
	onSelect,
}: {
	item: Item
	type: TabType
	onClose: () => void
	onSelect: (
		id: number,
		updates: { poster: string; title?: string; year?: number },
	) => void
} = $props()

interface SearchResult {
	id: string | number
	title: string
	year: string
	poster: string | null
	source: string
}

let query = $state(item.title)
let year = $state<string | number>(item.year || "")
let results = $state<SearchResult[]>([])
let searching = $state(false)
let source = $state<"tmdb" | "omdb">("tmdb")
let manualUrl = $state("")
let showManual = $state(false)

async function doSearch() {
	if (!query) return
	searching = true
	results = []

	const OMDB_KEY = import.meta.env.VITE_OMDB_KEY || ""

	if (source === "tmdb") {
		try {
			const searchResults = await searchTMDB(
				query,
				type === "series" ? "tv" : "movie",
				{ year },
			)
			results = searchResults.slice(0, 12).map((m) => ({
				id: m.id,
				title: m.title || m.name || "",
				year: (m.release_date || m.first_air_date)?.split("-")[0] || "",
				poster: getPosterUrl(m.poster_path),
				source: "TMDB",
			}))
		} catch {
			/* keep empty */
		}
	} else {
		const omdbType = type === "series" ? "series" : "movie"
		const yearParam = year ? `&y=${year}` : ""
		try {
			const res = await fetch(
				`${OMDB_BASE_URL}/?apikey=${OMDB_KEY}&s=${encodeURIComponent(query)}&type=${omdbType}${yearParam}`,
			)
			const data = await res.json()
			if (data.Search) {
				results = data.Search.slice(0, 12).map(
					(m: {
						imdbID: string
						Title: string
						Year: string
						Poster: string
					}) => ({
						id: m.imdbID,
						title: m.Title,
						year: m.Year,
						poster: m.Poster !== "N/A" ? m.Poster : null,
						source: "OMDb",
					}),
				)
			}
		} catch {
			/* keep empty */
		}
	}
	searching = false
}

$effect(() => {
	void query
	void year
	void source
	void type
	void doSearch()
})

function applyManualUrl() {
	if (manualUrl?.startsWith("http")) {
		onSelect(item.id, { poster: manualUrl })
	}
}

function selectResult(r: SearchResult) {
	if (!r.poster) return
	onSelect(item.id, {
		poster: r.poster,
		title: r.title,
		year: parseInt(r.year, 10) || item.year,
	})
}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="modal-bg" onclick={onClose} onkeydown={() => {}} role="presentation">
	<div
		class="modal fix-modal"
		onclick={(e) => e.stopPropagation()}
		onkeydown={(e) => e.stopPropagation()}
		role="dialog"
		aria-modal="true"
	>
		<div class="modal-head">
			<div class="modal-title">Fix poster</div>
			<button type="button" class="modal-close" onclick={onClose}>×</button>
		</div>
		<div class="modal-body">
			<div class="fix-search">
				<input
					type="text"
					class="search-box"
					bind:value={query}
					onkeydown={(e) => e.key === "Enter" && doSearch()}
					placeholder="Title"
					style="flex: 1"
				/>
				<input
					type="number"
					class="search-box year-input"
					bind:value={year}
					placeholder="Year"
				/>
				<button type="button" class="btn btn-primary" onclick={doSearch}>
					🔍
				</button>
			</div>

			<div class="source-toggle">
				<button
					type="button"
					class="source-btn"
					class:active={source === "tmdb"}
					onclick={() => (source = "tmdb")}
				>
					TMDB
				</button>
				<button
					type="button"
					class="source-btn"
					class:active={source === "omdb"}
					onclick={() => (source = "omdb")}
				>
					OMDb/IMDb
				</button>
			</div>

			{#if searching}<div class="searching">Searching...</div>{/if}

			<div class="fix-results">
				{#each results as r (r.id)}
					<button
						type="button"
						class="fix-result"
						class:no-poster={!r.poster}
						onclick={() => selectResult(r)}
					>
						{#if r.poster}
							<img src={r.poster} alt="" />
						{:else}
							<div class="fix-no-poster">No poster</div>
						{/if}
						<div class="fix-result-info">
							<div class="fix-result-title">{r.title}</div>
							<div class="fix-result-year">
								{r.year} · {r.source}
							</div>
						</div>
					</button>
				{/each}
			</div>

			{#if results.length === 0 && !searching}
				<div class="empty-small">No results. Try the original title.</div>
			{/if}

			<div class="manual-section">
				<button
					type="button"
					class="link-btn"
					onclick={() => (showManual = !showManual)}
				>
					{showManual ? "▼ Hide" : "▶ Paste image URL"}
				</button>
				{#if showManual}
					<div class="manual-url">
						<input
							type="text"
							class="search-box"
							bind:value={manualUrl}
							placeholder="https://..."
							style="flex: 1"
						/>
						<button type="button" class="btn btn-primary" onclick={applyManualUrl}>
							OK
						</button>
					</div>
				{/if}
			</div>
		</div>
	</div>
</div>

// src/components/FixPosterModal.jsx
import { useCallback, useEffect, useState } from "react"

const FixPosterModal = ({ item, type, onClose, onSelect }) => {
	const [query, setQuery] = useState(item.title)
	const [year, setYear] = useState(item.year || "")
	const [results, setResults] = useState([])
	const [searching, setSearching] = useState(false)
	const [source, setSource] = useState("tmdb")
	const [manualUrl, setManualUrl] = useState("")
	const [showManual, setShowManual] = useState(false)

	const doSearch = useCallback(async () => {
		if (!query) return
		setSearching(true)
		setResults([])

		const OMDB_KEY = import.meta.env.VITE_OMDB_KEY || ""

		if (source === "tmdb") {
			try {
				const results = await searchTMDB(
					query,
					type === "films" ? "movie" : "tv",
					{ year },
				)
				setResults(
					results.slice(0, 12).map((m) => ({
						id: m.id,
						title: m.title || m.name,
						year: (m.release_date || m.first_air_date)?.split("-")[0],
						poster: getPosterUrl(m.poster_path),
						source: "TMDB",
					})),
				)
			} catch (_e) {}
		} else {
			const omdbType = type === "films" ? "movie" : "series"
			const yearParam = year ? `&y=${year}` : ""
			try {
				const res = await fetch(
					`https://www.omdbapi.com/?apikey=${OMDB_KEY}&s=${encodeURIComponent(query)}&type=${omdbType}${yearParam}`,
				)
				const data = await res.json()
				if (data.Search) {
					setResults(
						data.Search.slice(0, 12).map((m) => ({
							id: m.imdbID,
							title: m.Title,
							year: m.Year,
							poster: m.Poster !== "N/A" ? m.Poster : null,
							source: "OMDb",
						})),
					)
				}
			} catch (_e) {}
		}
		setSearching(false)
	}, [query, year, source, type])

	useEffect(() => {
		doSearch()
	}, [doSearch])

	const applyManualUrl = () => {
		if (manualUrl?.startsWith("http")) {
			onSelect(item.id, { poster: manualUrl })
		}
	}

	const selectResult = (r) => {
		if (!r.poster) return
		onSelect(item.id, {
			poster: r.poster,
			title: r.title,
			year: parseInt(r.year, 10) || item.year,
		})
	}

	return (
		<div className="modal-bg" onClick={onClose}>
			<div className="modal fix-modal" onClick={(e) => e.stopPropagation()}>
				<div className="modal-head">
					<div className="modal-title">Corriger le film</div>
					<button type="button" className="modal-close" onClick={onClose}>
						×
					</button>
				</div>
				<div className="modal-body">
					<div className="fix-search">
						<input
							type="text"
							className="search-box"
							value={query}
							onChange={(e) => setQuery(e.target.value)}
							onKeyDown={(e) => e.key === "Enter" && doSearch()}
							placeholder="Titre"
							style={{ flex: 1 }}
						/>
						<input
							type="number"
							className="search-box year-input"
							value={year}
							onChange={(e) => setYear(e.target.value)}
							placeholder="Année"
						/>
						<button
							type="button"
							className="btn btn-primary"
							onClick={doSearch}
						>
							🔍
						</button>
					</div>

					<div className="source-toggle">
						<button
							type="button"
							className={`source-btn ${source === "tmdb" ? "active" : ""}`}
							onClick={() => setSource("tmdb")}
						>
							TMDB
						</button>
						<button
							type="button"
							className={`source-btn ${source === "omdb" ? "active" : ""}`}
							onClick={() => setSource("omdb")}
						>
							OMDb/IMDb
						</button>
					</div>

					{searching && <div className="searching">Recherche...</div>}

					<div className="fix-results">
						{results.map((r) => (
							<div
								key={r.id}
								className={`fix-result ${!r.poster ? "no-poster" : ""}`}
								onClick={() => selectResult(r)}
							>
								{r.poster ? (
									<img src={r.poster} alt="" />
								) : (
									<div className="fix-no-poster">Pas d'affiche</div>
								)}
								<div className="fix-result-info">
									<div className="fix-result-title">{r.title}</div>
									<div className="fix-result-year">
										{r.year} · {r.source}
									</div>
								</div>
							</div>
						))}
					</div>

					{results.length === 0 && !searching && (
						<div className="empty-small">
							Aucun résultat. Essayez le titre original.
						</div>
					)}

					<div className="manual-section">
						<button
							type="button"
							className="link-btn"
							onClick={() => setShowManual(!showManual)}
						>
							{showManual ? "▼ Masquer" : "▶ Coller une URL"}
						</button>
						{showManual && (
							<div className="manual-url">
								<input
									type="text"
									className="search-box"
									value={manualUrl}
									onChange={(e) => setManualUrl(e.target.value)}
									placeholder="https://..."
									style={{ flex: 1 }}
								/>
								<button
									type="button"
									className="btn btn-primary"
									onClick={applyManualUrl}
								>
									OK
								</button>
							</div>
						)}
					</div>
				</div>
			</div>
		</div>
	)
}

export default FixPosterModal
