// frontend-cinematheque/src/lib/components/ItemListRow.svelte
<script lang="ts">
import { getSmallPoster } from "$lib/poster"
import type { Item } from "$lib/types"
import { isConsumed } from "$lib/types"

let {
	item,
	onSelect,
	onToggleWatch,
}: {
	item: Item
	onSelect: (item: Item) => void
	onToggleWatch: (id: number, e: MouseEvent) => void
} = $props()

const creator = $derived(
	("director" in item && item.director) ||
		("creator" in item && item.creator) ||
		("author" in item && item.author),
)
const small = $derived(getSmallPoster(item.poster))
</script>

<button
	type="button"
	class="list-item"
	class:is-watched={isConsumed(item)}
	class:is-unwatched={!isConsumed(item)}
	onclick={() => onSelect(item)}
>
	{#if item.poster && small}
		<img class="list-poster" src={small} alt="" loading="lazy" />
	{:else}
		<div class="list-poster-empty">?</div>
	{/if}
	<div class="list-info">
		<div class="list-title">{item.title}</div>
		<div class="list-meta">
			{creator} · {item.year}
		</div>
	</div>
	<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
	<div
		class="watch-btn"
		class:watched={isConsumed(item)}
		onclick={(e) => {
			e.stopPropagation()
			onToggleWatch(item.id, e)
		}}
		onkeydown={(e) => e.stopPropagation()}
		role="checkbox"
		aria-checked={isConsumed(item)}
		tabindex="0"
	>
		✓
	</div>
</button>

// src/components/ItemListRow.tsx
import type { Item } from "@/types"
import { getSmallPoster } from "@/utils/poster"

interface ItemListRowProps {
	item: Item
	onSelect: (item: Item) => void
	onToggleWatch: (id: number, e: React.MouseEvent) => void
}

const ItemListRow = ({ item, onSelect, onToggleWatch }: ItemListRowProps) => {
	const creator =
		("director" in item && item.director) ||
		("creator" in item && item.creator) ||
		("author" in item && item.author)

	return (
		<button
			type="button"
			className={`list-item ${item.watched ? "is-watched" : "is-unwatched"}`}
			onClick={() => onSelect(item)}
		>
			{item.poster ? (
				<img
					className="list-poster"
					src={getSmallPoster(item.poster) ?? undefined}
					alt=""
					loading="lazy"
				/>
			) : (
				<div className="list-poster-empty">?</div>
			)}
			<div className="list-info">
				<div className="list-title">{item.title}</div>
				<div className="list-meta">
					{creator} · {item.year}
				</div>
			</div>
			{/* biome-ignore lint/a11y/useSemanticElements: styled watch button */}
			<div
				className={`watch-btn ${item.watched ? "watched" : ""}`}
				onClick={(e) => onToggleWatch(item.id, e)}
				onKeyDown={(e) => e.stopPropagation()}
				role="checkbox"
				aria-checked={item.watched}
				tabIndex={0}
			>
				✓
			</div>
		</button>
	)
}

export default ItemListRow
